package com.optician.backend.service;

import com.optician.backend.dto.ProductRequestDto;
import com.optician.backend.dto.ProductResponseDto;
import com.optician.backend.dto.ProductVariantRequestDto;
import com.optician.backend.exception.DuplicateResourceException;
import com.optician.backend.exception.ProductValidationException;
import com.optician.backend.exception.ResourceNotFoundException;
import com.optician.backend.mapper.ProductMapper;
import com.optician.backend.mapper.ProductVariantMapper;
import com.optician.backend.model.Product;
import com.optician.backend.model.ProductVariant;
import com.optician.backend.model.Stock;
import com.optician.backend.model.Store;
import com.optician.backend.model.enums.ProductType;
import com.optician.backend.repository.BrandRepository;
import com.optician.backend.repository.CategoryRepository;
import com.optician.backend.repository.ProductRepository;
import com.optician.backend.repository.ProductVariantRepository;
import com.optician.backend.service.impl.ProductServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;
    @Mock
    private BrandRepository brandRepository;
    @Mock
    private CategoryRepository categoryRepository;
    @Mock
    private ProductVariantRepository variantRepository;
    @Mock
    private ProductMapper productMapper;
    @Mock
    private ProductVariantMapper variantMapper;
    @Mock
    private ProductAuditService auditService;

    @InjectMocks
    private ProductServiceImpl productService;

    private ProductRequestDto sampleRequest;
    private Product sampleProduct;
    private ProductResponseDto sampleResponse;

    @BeforeEach
    void setUp() {
        sampleRequest = ProductRequestDto.builder()
                .reference("OPT-1001")
                .name("Ray-Ban Wayfarer")
                .productType(ProductType.SUNGLASSES)
                .build();

        sampleProduct = Product.builder()
                .id(1L)
                .reference("OPT-1001")
                .name("Ray-Ban Wayfarer")
                .productType(ProductType.SUNGLASSES)
                .active(true)
                .build();

        sampleResponse = ProductResponseDto.builder()
                .id(1L)
                .reference("OPT-1001")
                .name("Ray-Ban Wayfarer")
                .productType(ProductType.SUNGLASSES)
                .stock(0)
                .variantCount(0L)
                .build();
    }

    @Test
    @DisplayName("Should successfully create product when data is valid")
    void createProduct_Success() {
        when(productRepository.existsByReference("OPT-1001")).thenReturn(false);
        when(productMapper.toEntity(sampleRequest)).thenReturn(sampleProduct);
        when(productRepository.save(any())).thenReturn(sampleProduct);
        when(productMapper.toDto(sampleProduct)).thenReturn(sampleResponse);

        ProductResponseDto response = productService.createProduct(sampleRequest);

        assertNotNull(response);
        assertEquals("OPT-1001", response.getReference());
        assertEquals(0, response.getStock());
        assertEquals(0L, response.getVariantCount());
        verify(productRepository, times(1)).save(any());
    }

    @Test
    @DisplayName("Should throw DuplicateResourceException when reference already exists")
    void createProduct_DuplicateReference() {
        when(productRepository.existsByReference("OPT-1001")).thenReturn(true);

        assertThrows(DuplicateResourceException.class, () -> productService.createProduct(sampleRequest));
        verify(productRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should auto-generate a reference when none is provided")
    void createProduct_AutoGeneratedReference() {
        ProductRequestDto modelReq = ProductRequestDto.builder()
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .build();

        when(productRepository.existsByReference(anyString())).thenReturn(false);
        when(productMapper.toEntity(any())).thenReturn(sampleProduct);
        when(productRepository.save(any())).thenReturn(sampleProduct);
        when(productMapper.toDto(any())).thenReturn(sampleResponse);

        ProductResponseDto response = productService.createProduct(modelReq);

        assertNotNull(response.getReference());
        verify(productRepository, atLeastOnce()).existsByReference(anyString());
    }

    @Test
    @DisplayName("Should throw ProductValidationException when a nested variant has no SKU")
    void createProduct_VariantWithoutSku() {
        ProductRequestDto req = ProductRequestDto.builder()
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .variants(List.of(ProductVariantRequestDto.builder().build()))
                .build();

        when(productRepository.existsByReference(anyString())).thenReturn(false);
        when(productMapper.toEntity(any())).thenReturn(sampleProduct);

        assertThrows(ProductValidationException.class, () -> productService.createProduct(req));
        verify(productRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw DuplicateResourceException when a nested variant has a duplicate SKU")
    void createProduct_DuplicateVariantSku() {
        ProductRequestDto req = ProductRequestDto.builder()
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .variants(List.of(ProductVariantRequestDto.builder().sku("RB-X1").build()))
                .build();

        when(productRepository.existsByReference(anyString())).thenReturn(false);
        when(productMapper.toEntity(any())).thenReturn(sampleProduct);
        when(variantRepository.existsBySku("RB-X1")).thenReturn(true);

        assertThrows(DuplicateResourceException.class, () -> productService.createProduct(req));
        verify(productRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should retrieve product by ID")
    void getProductById_Success() {
        when(productRepository.findById(1L)).thenReturn(Optional.of(sampleProduct));
        when(productMapper.toDto(sampleProduct)).thenReturn(sampleResponse);

        ProductResponseDto result = productService.getProductById(1L);

        assertNotNull(result);
        assertEquals(1L, result.getId());
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when product does not exist")
    void getProductById_NotFound() {
        when(productRepository.findById(999L)).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () -> productService.getProductById(999L));
    }

    @Test
    @DisplayName("Should create a commercial model without any variant data")
    void createProduct_CommercialModelOnly_Success() {
        ProductRequestDto modelReq = ProductRequestDto.builder()
                .reference("RX5228")
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .model("RX5228")
                .frameShape(com.optician.backend.model.enums.FrameShape.RECTANGULAIRE)
                .build();

        Product savedEntity = Product.builder()
                .id(2L)
                .reference("RX5228")
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .model("RX5228")
                .status(com.optician.backend.model.enums.ProductStatus.ACTIF)
                .build();

        ProductResponseDto expectedResp = ProductResponseDto.builder()
                .id(2L)
                .reference("RX5228")
                .name("Ray-Ban RX5228")
                .productType(ProductType.OPTICAL_FRAME)
                .status(com.optician.backend.model.enums.ProductStatus.ACTIF)
                .stock(0)
                .price(null)
                .variantCount(0L)
                .build();

        when(productRepository.existsByReference("RX5228")).thenReturn(false);
        when(productMapper.toEntity(any())).thenReturn(savedEntity);
        when(productRepository.save(any())).thenReturn(savedEntity);
        when(productMapper.toDto(any())).thenReturn(expectedResp);

        ProductResponseDto result = productService.createProduct(modelReq);

        assertNotNull(result);
        assertEquals("Ray-Ban RX5228", result.getName());
        assertEquals(com.optician.backend.model.enums.ProductStatus.ACTIF, result.getStatus());
        verify(productRepository, times(1)).save(any());
    }

    @Test
    @DisplayName("Product derives stock and price from variants and stocks (no direct storage)")
    void productDerivesStockAndPriceFromVariants() {
        Product product = Product.builder()
                .id(10L)
                .reference("RX5228")
                .name("Ray-Ban RX5228")
                .build();

        Store tunis = Store.builder().id(1L).name("OptiVision Tunis").build();
        Store sousse = Store.builder().id(2L).name("OptiVision Sousse").build();
        Store sfax = Store.builder().id(3L).name("OptiVision Sfax").build();

        ProductVariant noir = ProductVariant.builder()
                .sku("RB-RX5228-BLK").active(true)
                .sellingPrice(new BigDecimal("450.00"))
                .build();
        ProductVariant ecaille = ProductVariant.builder()
                .sku("RB-RX5228-HVN").active(true)
                .sellingPrice(new BigDecimal("470.00"))
                .build();
        ProductVariant inactif = ProductVariant.builder()
                .sku("RB-RX5228-OFF").active(false)
                .sellingPrice(new BigDecimal("500.00"))
                .build();

        noir.setStocks(List.of(
                Stock.builder().store(tunis).quantity(5).build(),
                Stock.builder().store(sousse).quantity(3).build()
        ));
        ecaille.setStocks(List.of(
                Stock.builder().store(sfax).quantity(7).build()
        ));
        inactif.setStocks(List.of(
                Stock.builder().store(tunis).quantity(99).build()
        ));

        product.setVariants(List.of(noir, ecaille, inactif));

        assertEquals(3L, product.getVariantCount());
        // Stock total = 5 + 3 + 7 + 99 (toutes les variantes, tous les magasins)
        assertEquals(114, product.getStock());
        // Prix à partir de : minimum des variantes ACTIVES uniquement
        assertEquals(450.0, product.getPrice());
    }
}
