package com.optician.backend.model.enums;

public enum AuditAction {
    // Produit
    CREATE,
    UPDATE,
    DELETE,
    ACTIVATE,
    DEACTIVATE,
    PRICE_CHANGE,
    REFERENCE_CHANGE,
    ARCHIVE,

    // Stock
    STOCK_ENTRY,
    STOCK_EXIT,
    STOCK_ADJUSTMENT,
    STOCK_TRANSFER_CREATED,
    STOCK_TRANSFER_APPROVED,
    STOCK_TRANSFER_RECEIVED,
    STOCK_TRANSFER_CANCELLED,
    STOCK_INVENTORY_CREATED,
    STOCK_INVENTORY_VALIDATED,
    STOCK_RESERVATION_CREATED,
    STOCK_RESERVATION_RELEASED,
    STOCK_THRESHOLD_CHANGE,

    // Permissions / Sécurité
    PERMISSION_CHANGE
}
